version: 2.1

orbs:
  node: circleci/node@4.0.0
  codecov: codecov/codecov@1.2.3

jobs:
  test:
    docker:
      - image: circleci/node:14.17.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn cover
      - codecov/upload:
          file: coverage/*.json
      - run: yarn chromatic --project-token=${CHROMATIC_TOKEN}
  versioning:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Check packege version
          command: node scripts/check-version arthur-v-kasper 3dino_academy

workflows:
  ci:
    jobs:
      - test
      - versioning:
          filters:
            branches:
              ignore: main
            tags:
              ignore: /.*/
